### ISSUE TITLE
Exclude filter parameter is not being utilized because the attribute name is incorrect.

### ISSUE THREAD

**Issue by hammzj** [agardiner/csv-diff#16]
## Issue Location
https://github.com/agardiner/csv-diff/blob/10701f441eca5329db864d771433bae494dae6d9/lib/csv-diff/source.rb#L118

### Compare to
https://github.com/agardiner/csv-diff/blob/10701f441eca5329db864d771433bae494dae6d9/lib/csv-diff/source.rb#L147-L164

***

Everywhere else in the file, `@exclude` is being used but it comes up empty because it's never been declared. 
Please make this correction to allow the exclusion filter to be utilized again.

**Comment by hammzj** [comment]
@agardiner I can do this for you and issue a PR once I make the change, if you'd prefer.

**Comment by agardiner** [comment]
Thanks for catching this. Typo fixed in #0f646f.

**Comment by hammzj** [comment]
I see it. Will you need to push a gem version 0.6.1 for this? Still showing as 0.6.0 on the master branch and I did not get an update on my machine when I pulled it from our company's gem server (which updates daily).

**Comment by agardiner** [comment]
Version 0.6.1 has now been pushed to rubygems.
